# Generated by Django 2.2.5 on 2019-09-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('overview', models.TextField()),
                ('pack', models.CharField(max_length=15)),
                ('usage', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('minimum_set', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
